[package]
name = "rust"
version = "0.1.0"
authors = ["blukai <20866892+blukai@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[dependencies.sdl2]
version = "0.32.2"
default-features = false
features = ["gfx"]
